language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7 MODELDICT=1.2.0
  - DJANGO=1.3.1 MODELDICT=1.2.0
  - DJANGO=1.4 MODELDICT=1.2.0
  - DJANGO=1.5 MODELDICT=1.2.0
  - DJANGO=1.2.7 MODELDICT=1.4.1
  - DJANGO=1.3.1 MODELDICT=1.4.1
  - DJANGO=1.4 MODELDICT=1.4.1
  - DJANGO=1.5 MODELDICT=1.4.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-modeldict==$MODELDICT --use-mirrors
  - pip install -q flake8 --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - make test
